name: django-test

on:
  # Trigger the workflow on push or pull request,
  # but only for branches other than master
  push:
    branches-ignore:
      - master
  pull_request:
    branches-ignore:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:9.6
    container:
      image: python:3.6
      env:
        POSTGRES_DB: django
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: ""
        DJANGO_ENV: staging
        SECRET_KEY: test
        ALLOWED_HOSTS: "*"
        WEB_URL: "http://localhost:3000"
        AWS_ACCESS_KEY_ID: "test"
        AWS_SECRET_ACCESS_KEY: "test"
        AWS_STORAGE_BUCKET_NAME: "test"
        AWS_LOCATION: "test"
        AWS_DEFAULT_REGION: "test"
        AWS_QUERYSTRING_AUTH: False
        SEND_MAIL: False
        SENDGRID_API_KEY: "test"
        FACEBOOK_APP_ID: "test"
        FACEBOOK_APP_CLIENT_TOKEN: "test"
        FACEBOOK_APP_SECRET: "test"
        FACEBOOK_SUCCESSFUL_LOGIN_URL: "test"
        GOOGLE_CLIENT_ID: "test"
        GOOGLE_CLIENT_SECRET: "test"
        GOOGLE_SUCCESSFUL_LOGIN_URL: "test"
        GOOGLE_PROJECT_ID: "test"
        GOOGLE_REDIRECT_URI: "test"
    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        export DATABASE_URL=postgres://postgres:@postgres:5432/django
        apt-get update -qy
        apt-get install -y python3-dev python3-pip
        pip3 install -r requirements.txt
        python3 manage.py test apps
